export default{
    searchInputBox:"[id='search'] input",
    searchctrl:"//i[@class='fas fa-search']",
    editctrl:"(//i[contains(@class,'fas fa-table')])[1]",
    collectionNameInput:"//span[text()='collectionName']",
    newCollectionBtn:'[aria-label="Create Collection"]',
    nameInputTxtBx:'[id="name"]',
    descriptionInputTxtBx:'[id="description"]',
    createscreenForInputDropdown: '//label[normalize-space(text())="Create Screen"]//following-sibling::div/div',
    createscreenInputTxtBx: '[name="create_screen_id"]',
    screenDropdownOption: '//li[@role="option"]//span[text()="screenName"]',
    viewScreenForInputDropdown:"//label[normalize-space(text())='View Screen']//following-sibling::div/div",
    viewScreenInputTxtBx: '[name="read_screen_id"]',
    editScreenForInputDropdown:"//label[normalize-space(text())='Edit Screen']//following-sibling::div/div",
    editScreenInputTxtBx: '[name="update_screen_id"]',
    collectionsaveBtn:"//button[text()='Save']",
    newRecordBtn:'[id="addUserCollection"]',
    dateinputTxtBx:'(//*[@type="text"])[1]',
    titleInputTxtBx:'[name="title"]',
    authorInputTxtBx:'[name="author"]',
    priceInputTxtBx:'[name="price"]',
    submitBtn:'[class="btn btn-primary"]',
    navEditBtn:'[id="nav-edit-record-tab"]',
    collectionNameInput:'//a[text()[normalize-space()="name"]]'
}