export default{
    prrocessEvent: '(//div[@title="eventName"])[index]',
    recentlyDropedEvent: '[data-type="processmaker.components.nodes.eventName.Shape"]',
    zoomOutBtn: '[data-test="zoom-out"]',
    saveBtn: '[title="Save"]',
    saveBtnInPopUp: '//button[text()="Save"]',
    saveChangesModal: '//h5[text()="Commit Changes"]',
    addProcessBtn: '[aria-label="Create Process"]',
    nameTxtBx: '[name="name"]',
    descriptionTxtBx: '[name="description"]',
    saveBtnToAddProcess: '//button[text()="Save"]',
    screenForInputDropdown: '//label[text()="Screen for Input"]//following-sibling::div/div[@class="multiselect__select"]',
    screenInputTxtBx: '[placeholder="type here to search"]',
    screenDropdownOption: '//li[@role="option"]//span[text()="screenName"]',
    screenForDisplayDropdown: '//label[text()="Select a Display Screen"]//following-sibling::div/div[@class="multiselect__select"]',
    expandLoopActivityBtn: '[aria-label="Loop Activity"] button[aria-expanded="false"]',
    loopModeDropdown: '//legend[text()="Loop Mode"]/following-sibling::div/select',
    requestVarArrayTxtBx: '//label[text()="Request Variable Array"]/following-sibling::div/input',
    addManualTask: '[data-test="switch-to-manual-task"]',
    iterationTextBox: '//*[@data-cy="loopMaximum"]',
    conditionTextBox:'//*[@data-cy="loopCondition"]',
    searchInputProcess: '(//input[@placeholder="Search"])[1]',
    //searchBox: '(//div[contains(@class,"pagination-nav-item item")])[1]',
    searchBox:"(//button[@class='btn btn-primary'])[1]",
    configureBtn: '(//button[@class="btn btn-link"]//i)[2]',
    processNameInputTxt:'//span[text()="processName"]',
    processManagerDropdown: '//label[text()="Process Manager"]//following-sibling::div/div[@class="multiselect__select"]',
    processMangerInput: '//label[text()="Process Manager"]/parent::div//div//div//div/following-sibling::input',
    processInputTxt: '(//input[@class="multiselect__input"])[2]',
    processManagerDropdownOption: '//label[text()="Process Manager"]//parent::div//span[text()[normalize-space()="Admin User"]]',
    processManagerEditSaveBtn: '//label[text()="Status"]/parent::div/following-sibling::div//button[text()="Save"]',
    scripttaskBtn: '[data-test="switch-to-script-task"]',
    screenForScriptDropdown:'.multiselect__select',
    dataConnectorDropdown:'//label[text()="Select a Data Connector"]//following-sibling::div/div[@class="multiselect__select"]',
    dataConnectorInputtxtBx:'[placeholder="Select a Data Connector"]',
    dataconnectorListDropdown: '//label[text()="Select a Resource"]//following-sibling::div/div[@class="multiselect__select"]',
    dataConnectorListInputtxtBx:'[placeholder="Select a Resource"]',
    listInputoption: '//li[@role="option"]//span//span[text()[normalize-space()="listName"]]',
    nameInput:'[name="name"]',
    eventBasedGatewayBtn:"[data-test='switch-to-event-based-gateway']",
    intermediateSignalCatchEvent:"[data-test='switch-to-intermediate-signal-catch-event']",
    signalForInputDropdown: '//label[text()="Signal"]//following-sibling::div//div//div[@class="multiselect__select"]',
    signalInputTxtBx: '[placeholder="Select option"]',
    signalDropdownOption: '//li[@role="option"]//span[text()="signalName"]',
    configDropDown:"(//i[@class='when-opened fas fa-chevron-down accordion-arrow ml-auto'])[1]",
    assignRules:"//span[text()='Assignment Rules']",
    userDropDown:"[id='assignmentsDropDownList']",
    userGroupOption:"[value='user_group']",
    assignedUsersOption:"//label[text()='Assigned Users/Groups']/parent::div/child::div",
    useroption:"//li[@role='option']//span//span[contains(text(),'userName')]",
    usertxtInput:"(//*[@placeholder='type here to search'])[2]",
    responseMappingbtn:"//a[@data-cy='inspector-add-option']",
    responseMappingSrcInput:"[data-cy='inspector-option-value']",
    responseMappingVarInput:"[data-cy='inspector-option-key']",
    resMappingSaveBtn:"[data-cy='inspector-option-save']",
    resMappingEditOption:"//a[@data-cy='inspector-options-edit']",
    terminateEndEventBtn:"[data-test='switch-to-terminate-end-event']",
    pdfFileNameInput:"[name='PDF File Name']"
}