export default{
    addScreenButton: 'button[aria-label="Create Screen"]',
    nameTxtBx: 'input[name="title"]',
    descriptionTxtBx: '[name="description"]',
    typeDropDown: 'select[name="type"]',
    saveBtn: '//button[text()="Save"]',
    varaibleNameTxtBx: '[name="Variable Name"]',
    dataSourceDropDown: 'select#data-sources',
    allowMultipleSelections: '//div[text()[normalize-space()="Allow Multiple Selections"]]/input',
    typeOfReturnedValue: 'select#value-type-returded',
    dataSourceSectionBtn: 'button[data-cy="accordion-DataSource"]',
    optionsVaraibleTxtBx: 'input[placeholder="Request Variable Name"]',
    dataConnectorDropDown: 'select#data-sources-list',
    contentTxtBx: 'input#value',
    endPointDropDown: 'select#endpoint-list',
    richTextContentTxtArea: '[data-cy="inspector-content"]',
    saveScreenBtn: 'button[title="Save Screen"]',
    saveVersionsBtn: 'button[title="Save Versions"]',
    optionsLabelTxtBx:"[data-cy='inspector-options-label']",
    variableDataProTxtBx:"[data-cy='inspector-options-value']",
    labelNameTxtBx:'[data-cy="inspector-label"]',
    dateDropDownbtn:"(//div[@data-cy='inspector-dataFormat']//div)[1]",
    dateValueBx:"//span[text()='type']"
}